import Head from "next/head";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Wannado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hallo!</h1>
    </>
  );
}
